<div class="container-fluid bg-white">
    <nav class="navigation row">
        <div class="col-xs-6 ta-l">
            <a href="/">
                <img class="logo logo--small" src="/assets/images/logo-dark.png">
            </a>
        </div>
        <div class="col-xs-6 ta-r">
            <a class="testio-logout button button--navigation" href="/logout">Logout</a>
        </div>
    </nav>
</div>